name: Issue
description: "File a report for a bug/issue inside of TransSocial"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help us improve TransSocial! Please note that these tickets are to be treated seriously, any content deemed disrespectful, non-serious, or does not adequately follow the steps below will be immediately closed and potentially removed.

        This is an English-only form. If you do not speak English, please use Google Translate or similar to translate into English.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: "Please select the type of browser that you were using. If you're unsure, you can search `What browser engine does YOUR_BROWSER use?`. If you use the app, please leave this blank."
      multiple: true
      options:
          - Chromium-based
          - Firefox-based
          - WebKit-based
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: "What operating system did you experience this on?"
      multiple: true
      options:
          - Windows 8.1 or older
          - Windows 10
          - Windows 11
          - macOS
          #- KatOS
          - Debian-based Linux OS (Debian, Deepin, etc.)
          - Arch-based Linux OS (Arch, Manjaro, etc.)
          - Ubuntu-based Linux OS (Ubuntu, Linux Mint, etc.)
          - Fedora-based Linux OS  (Fedora, Red Hat Enterprise Linux, etc.)
          - Slackware-based Linux OS (Slackware, openSUSE, etc.)
          - Other (please let us know in the description!)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: "Provide a description of the issue you are reporting."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: "Step-by-step process on how to reproduce the issue. Be short and to the point. If you're unsure, leave this blank."
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Verification of Submission
      description: Verify that you have selected options above and filled out request properly and in full. 
      options:
        - label: I agree that I properly filled out the items listed above.
          required: true
        - label: I understand an issue may be closed if process is not properly followed.
          required: true 
        - label: I could replicate this issue in a local development environment
          required: false
        - label: I will resolve this issue myself
          required: false 
        - label: I have searched for similar issues
          required: true