services:
    tusd:
        build:
            dockerfile: Dockerfile
        user: "1111:1111"
        command: -verbose -behind-proxy -hooks-dir /hooks -cors-allow-origin http://localhost:5173 -cors-max-age 3600 -upload-dir=/data/progress
        volumes:
            - data:/data
        restart: unless-stopped
    proxy:
        image: nginxinc/nginx-unprivileged:latest
        user: "1111:1111"
        ports:
            - 6979:8080
        volumes:
            - data:/data
            - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        restart: unless-stopped

volumes:
    data:
