name: Deploy to Cloudflare Pages
on:
  workflow_dispatch:
  push:
    branches:
      - "**"

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm install
        working-directory: ./web
      
      - name: Write .env file
        run: |
          printf "%s" "${{ secrets.CANARY_ENV_FILE }}" > ./web/.env
      
      - name: Build project
        run: npm run build
        working-directory: ./web
    
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/rewrite'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./web
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=auride
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}